name: tests
on: [push, pull_request]
jobs:

  test:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        go-version:
          - '1.17'
          - '1.18'
    name: Go ${{ matrix.go-version }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go-version }}
      - name: Test
        run: go test ./...
